# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Singularity Lawyer
email: apkritikos@singularity.lawyer
description: >- # this means to ignore newlines until "baseurl:"
  Intellectual Property (IP) Attorney & Software Engineer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://singularity.lawyer" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  apkrit
linkedin_username:  apkritikos

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

header_pages:
  - index.md
  - about.md
  - news.md
  - tech.md
  - contact.md

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: false
  order: -1
  trail: 
    before: 1
    after: 1

############################################################


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
